version: "3.8"

volumes:
   # pgdata: 
    #kongadata:

services:    
    #################################
    # Employee: The Employee microservice
    #################################
    employee:
        build:
            context: ./
            dockerfile: employee.Dockerfile      
        image: amandateo2019/employee:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/lms
            PYTHONUNBUFFERED: 1
        ports:
            - "5006:5006"


    ###############################################
    # course: The course microservice
    ###############################################
    course:
        build:
            context: ./
            dockerfile: course.Dockerfile
        image: amandateo2019/course:1.0
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/lms
            PYTHONUNBUFFERED: 1
        ports:
            - "5007:5007"


    ###############################################
    # prereq: The prereq microservice
    ###############################################
    prereq:
        build:
            context: ./
            dockerfile: prereq.Dockerfile
        image: amandateo2019/prereq:1.0
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/lms
            PYTHONUNBUFFERED: 1
        ports:
            - "5008:5008"

    ###############################################
    # signupList: The signupList microservice
    ###############################################
    signupList:
        build:
            context: ./
            dockerfile: signupList.Dockerfile
        image: amandateo2019/signupList:1.0
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/lms
            PYTHONUNBUFFERED: 1
        ports:
            - "5009:5009"

    ###############################################
    # learner: The learner microservice
    ###############################################
    learner:
        build:
            context: ./
            dockerfile: learner.Dockerfile
        image: amandateo2019/learner:1.0
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/lms
            PYTHONUNBUFFERED: 1
        ports:
            - "5010:5010"


    ###############################################
    # class: The class microservice
    ###############################################
   # guess:
    #    build:
     #       context: ./
      #      dockerfile: class.Dockerfile
       # image: amandateo2019/class:1.0
        #environment:
         #   dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/lms
          #  PYTHONUNBUFFERED: 1
        #ports:
         #   - "5011:5011"

    ###############################################
    # Quiz: The quiz microservice
    ###############################################
    #guess:
     #   build:
      #      context: ./
       #     dockerfile: quiz.Dockerfile
        #image: amandateo2019/quiz:1.0
        #environment:
          #  dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/lms
           # PYTHONUNBUFFERED: 1
        #ports:
         #   - "5012:5012"
